# Generated by Django 3.2.2 on 2021-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210618_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
