# Generated by Django 3.2.2 on 2021-06-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210617_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.CharField(max_length=100, verbose_name='작성자'),
        ),
    ]
