# Generated by Django 3.2.2 on 2021-06-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
